# Конфигурация SpigotVisylogger
# Временное окно для отслеживания активности (в секундах)
time-window: 300  # 5 минут

# Максимальная скорость движения игрока без предупреждения (блоки/секунда)
max-speed: 12.0

# Интервал проверки скорости (в тиках, 20 тиков = 1 секунда)
speed-check-interval: 20

# Включить отладочные сообщения
debug: false

# Материалы для отслеживания
# Формат: МАТЕРИАЛ:КОЛИЧЕСТВО_ЗА_ВРЕМЕННОЕ_ОКНО
watched-materials:
  materials:
    - "DIAMOND:32"           # 32 алмаза за 5 минут
    - "EMERALD:16"           # 16 изумрудов за 5 минут
    - "NETHERITE_SCRAP:8"    # 8 незеритовых обломков за 5 минут
    - "ANCIENT_DEBRIS:4"     # 4 древних обломка за 5 минут
    - "GOLD_INGOT:64"        # 64 золотых слитка за 5 минут
    - "IRON_INGOT:128"       # 128 железных слитков за 5 минут
    - "DIAMOND_ORE:32"       # 32 алмазных руды за 5 минут
    - "DEEPSLATE_DIAMOND_ORE:32"  # 32 глубинносланцевых алмазных руды за 5 минут
    - "EMERALD_ORE:16"       # 16 изумрудных руды за 5 минут
    - "DEEPSLATE_EMERALD_ORE:16"  # 16 глубинносланцевых изумрудных руды за 5 минут

# Сообщения
messages:
  prefix: "§c[VisyLogger]§r "
  mining-alert: "§e{player} добыл §c{amount}§e {material} §eза §c{time}§e секунд!"
  speed-alert: "§e{player} §eдвижется подозрительно быстро! Скорость: §c{speed}§e м/с"

# Дополнительные настройки
settings:
  # Проверять скорость только для игроков в режиме выживания
  check-survival-only: true

  # Минимальное расстояние для расчета скорости (блоки)
  min-distance-for-speed: 0.1
