name: SpigotVisylogger
version: '1.0.0'
main: com.visy.SpigotVisylogger.spigotVisylogger;
api-version: 1.20
authors: [YourName]
description: Plugin for monitoring suspicious player activity
website: https://yourwebsite.com

commands:
  visylogger:
    description: Main command for SpigotVisylogger
    usage: /<command> [reload|info|help]
    permission: visylogger.admin
    aliases: [vlogger, vl]

permissions:
  visylogger.admin:
    description: Allows access to VisyLogger admin commands
    default: op