commands:
  visylogger:
    description: Main command for SpigotVisylogger
    usage: /<command> [reload|info|help]
    permission: visylogger.admin
    aliases: [vlogger, vl]

permissions:
  visylogger.admin:
    description: Allows access to VisyLogger admin commands
    default: op
